<<<<<<< HEAD
import type { Metadata } from 'next';
import "./globals.css";
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'StudyBoard',
  description: 'A study group task coordination app',
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 0c3375f6842a5d8133b3181a3dd6fa29acc5852a
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
=======
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
>>>>>>> 0c3375f6842a5d8133b3181a3dd6fa29acc5852a
